export const trendingChannels = [
  {
    id: 1,
    title: "Neo-Pulse Music Festival",
    subtitle: "Channel 102 • Night Session",
    viewers: "842K Viewers",
    image: "/assets/images/chanel-image-1.png",
    icon: "music",
    is1080p: true,
  },
  {
    id: 2,
    title: "Global News Network",
    subtitle: "Prime Time Update",
    viewers: "1.2M Viewers",
    image: "/assets/images/chanel-image-2.png",
    icon: "globe",
    is1080p: false,
  },
  {
    id: 3,
    title: "Pro-Gaming Invitational",
    subtitle: "Grand Semi-Finals",
    viewers: "450K Viewers",
    image: "/assets/images/chanel-image-3.png",
    icon: "gamepad",
    is1080p: false,
  },
  {
    id: 4,
    title: "Culinary Masters Live",
    subtitle: "Fusion Night Special",
    viewers: "120K Viewers",
    image: "/assets/images/chanel-image-1.png",
    icon: "utensils",
    is1080p: false,
  },
  {
    id: 5,
    title: "Culinary Masters Live",
    subtitle: "Fusion Night Special",
    viewers: "120K Viewers",
    image: "/assets/images/chanel-image-2.png",
    icon: "utensils",
    is1080p: false,
  },
  {
    id: 6,
    title: "Culinary Masters Live",
    subtitle: "Fusion Night Special",
    viewers: "120K Viewers",
    image: "/assets/images/chanel-image-3.png",
    icon: "utensils",
    is1080p: false,
  },
  {
    id: 7,
    title: "Culinary Masters Live",
    subtitle: "Fusion Night Special",
    viewers: "120K Viewers",
    image: "/assets/images/chanel-image-1.png",
    icon: "utensils",
    is1080p: false,
  },
];
