export interface Movie {
  id: number;
  title: string;
  slug: string;
  description: string;
  image: string;
  year: number;
  duration: string;
  rating: number;
  genres: string[];
  languages: string[];
  quality: string;
  pgRating: string;
  label?: string; // Upcoming er jonno extra fields
  subtitle?: string;
  releaseDate?: string;
}

export const FEATURED_MOVIES: Movie[] = [
  {
    id: 1,
    title: "Black Panther: Wakanda Forever",
    slug: "black-panther-wakanda-forever",
    description:
      "The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King T'Challa.",
    image: "/assets/images/blcak-panther.jpg",
    year: 2022,
    duration: "2h 41m",
    rating: 6.7,
    genres: ["Action", "Adventure", "Drama"],
    languages: ["English", "Spanish"],
    quality: "HD / 4K",
    pgRating: "PG-13",
  },
  {
    id: 2,
    title: "Morbius",
    slug: "morbius",
    description:
      "Biochemist Michael Morbius tries to cure himself of a rare blood disease, but he inadvertently infects himself with a form of vampirism.",
    image: "/assets/images/morbius.png",
    year: 2022,
    duration: "1h 44m",
    rating: 5.2,
    genres: ["Action", "Adventure", "Horror"],
    languages: ["English"],
    quality: "HD",
    pgRating: "PG-13",
  },
  {
    id: 3,
    title: "Doctor Strange",
    slug: "doctor-strange",
    description:
      "In an accident, Stephen Strange, a famous neurosurgeon, loses the ability to use his hands. He goes to visit the mysterious Ancient One.",
    image: "/assets/images/doctor-strange.jpg",
    year: 2016,
    duration: "1h 55m",
    rating: 7.5,
    genres: ["Action", "Adventure", "Fantasy"],
    languages: ["English", "Hindi"],
    quality: "HD / 4K",
    pgRating: "PG-13",
  },
  {
    id: 4,
    title: "Jumanji: The Next Level",
    slug: "jumanji-the-next-level",
    description:
      "The gang is back but the game has changed. As they return to rescue one of their own, they discover that nothing is as they expect.",
    image: "/assets/images/jumanji.jpg",
    year: 2019,
    duration: "2h 3m",
    rating: 6.7,
    genres: ["Action", "Adventure", "Comedy"],
    languages: ["English", "Spanish"],
    quality: "HD",
    pgRating: "PG-13",
  },
  {
    id: 5,
    title: "The Mother",
    slug: "the-mother",
    description:
      "An assassin comes out of hiding to protect the daughter she gave up years before, while on the run from dangerous men.",
    image: "/assets/images/mother.png",
    year: 2023,
    duration: "1h 55m",
    rating: 5.6,
    genres: ["Action", "Thriller"],
    languages: ["English"],
    quality: "HD",
    pgRating: "R",
  },
];

export const UPCOMING_MOVIES: Movie[] = [
  {
    id: 1,
    title: "AVENGERS: DOOMSDAY",
    slug: "avengers-doomsday",
    label: "Marvel Studios",
    subtitle: "The Multiverse Collapses",
    description:
      "A new era of the MCU begins as Doctor Doom rises to reshape reality. The remaining heroes must unite for the ultimate stand against the void.",
    image: "/assets/images/avengers-doom-2.jpg",
    releaseDate: "01/05/2026",
    year: 2026,
    duration: "2h 45m",
    rating: 0.0,
    genres: ["Action", "Sci-Fi", "Adventure"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
  },
  {
    id: 2,
    title: "THE BATMAN PART II",
    slug: "the-batman-part-ii",
    label: "DC Studios",
    subtitle: "Deep in the Shadows",
    description:
      "Robert Pattinson returns as the Dark Knight. As Gotham faces a chilling new threat, Bruce Wayne must decide what he's willing to sacrifice for justice.",
    image: "/assets/images/the-batman-2a (2).webp",
    releaseDate: "02/10/2026",
    year: 2026,
    duration: "2h 50m",
    rating: 0.0,
    genres: ["Action", "Crime", "Drama"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "R",
  },
  {
    id: 3,
    title: "DUNE: THE PROPHET",
    slug: "dune-the-prophet",
    label: "Warner Bros",
    subtitle: "The Desert War",
    description:
      "Paul Atreides continues his journey as the leader of the Fremen, navigating political intrigue and mystical visions on the sands of Arrakis.",
    image: "/assets/images/dune-prophecy-.jpg",
    releaseDate: "18/12/2026",
    year: 2026,
    duration: "2h 35m",
    rating: 0.0,
    genres: ["Adventure", "Sci-Fi", "Drama"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "PG-13",
  },
];

export const ALL_MOVIES: Movie[] = [
  {
    id: 1,
    title: "Black Panther: Wakanda Forever",
    slug: "black-panther-wakanda-forever",
    description:
      "The people of Wakanda fight to protect their home from intervening world powers.",
    image: "/assets/images/blcak-panther.jpg",
    year: 2022,
    duration: "2h 41m",
    rating: 6.7,
    genres: ["Action", "Adventure"],
    languages: ["English", "Spanish"],
    quality: "HD / 4K",
    pgRating: "PG-13",
  },
  {
    id: 2,
    title: "Morbius",
    slug: "morbius",
    description:
      "Biochemist Michael Morbius tries to cure himself of a rare blood disease.",
    image: "/assets/images/morbius.png",
    year: 2022,
    duration: "1h 44m",
    rating: 5.2,
    genres: ["Action", "Horror"],
    languages: ["English"],
    quality: "HD",
    pgRating: "PG-13",
  },
  {
    id: 3,
    title: "Doctor Strange: Multiverse of Madness",
    slug: "doctor-strange-multiverse-of-madness",
    description:
      "Doctor Strange teams up with a mysterious teenage girl to traverse the multiverse.",
    image: "/assets/images/doctor-strange.jpg",
    year: 2022,
    duration: "2h 6m",
    rating: 6.9,
    genres: ["Action", "Fantasy"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "PG-13",
  },
  {
    id: 4,
    title: "Jumanji: The Next Level",
    slug: "jumanji-the-next-level",
    description:
      "The gang is back but the game has changed. They must brave unknown parts.",
    image: "/assets/images/jumanji.jpg",
    year: 2019,
    duration: "2h 3m",
    rating: 6.7,
    genres: ["Adventure", "Comedy"],
    languages: ["English", "Spanish"],
    quality: "HD",
    pgRating: "PG-13",
  },
  {
    id: 5,
    title: "The Mother",
    slug: "the-mother",
    description:
      "A deadly assassin comes out of hiding to protect the daughter she gave up.",
    image: "/assets/images/mother.png",
    year: 2023,
    duration: "1h 55m",
    rating: 5.6,
    genres: ["Action", "Thriller"],
    languages: ["English"],
    quality: "HD",
    pgRating: "R",
  },
  {
    id: 6,
    title: "RDX: Robert Dony Xavier",
    slug: "rdx-robert-dony-xavier",
    description:
      "Three friends reunite to take down a local gang in this high-octane action thriller.",
    image: "/assets/images/robart-darny-dexter.png",
    year: 2023,
    duration: "2h 30m",
    rating: 7.2,
    genres: ["Action", "Thriller"],
    languages: ["Malayalam", "Hindi"],
    quality: "HD",
    pgRating: "UA",
  },
  {
    id: 7,
    title: "The Perfection",
    slug: "the-perfection",
    description:
      "A troubled musical prodigy seeks out her former mentor's new star pupil.",
    image: "/assets/images/the-prefection.png",
    year: 2018,
    duration: "1h 30m",
    rating: 6.1,
    genres: ["Horror", "Drama"],
    languages: ["English"],
    quality: "HD",
    pgRating: "R",
  },
  {
    id: 8,
    title: "Extraction",
    slug: "extraction",
    description:
      "A black-market mercenary is hired to rescue the kidnapped son of an imprisoned crime lord.",
    image: "/assets/images/extraction.png",
    year: 2020,
    duration: "1h 56m",
    rating: 6.8,
    genres: ["Action", "Thriller"],
    languages: ["English", "Hindi"],
    quality: "HD / 4K",
    pgRating: "R",
  },
  {
    id: 9,
    title: "Jagame Thandhiram",
    slug: "jagame-thandhiram",
    description:
      "A clever, carefree gangster is recruited to help an overseas crime lord.",
    image: "/assets/images/jhuma-thareadima.png",
    year: 2021,
    duration: "2h 38m",
    rating: 5.8,
    genres: ["Action", "Crime"],
    languages: ["Tamil", "Hindi"],
    quality: "HD",
    pgRating: "UA",
  },
  {
    id: 10,
    title: "The Irishman",
    slug: "the-irishman",
    description:
      "An old man recalls his time as a hitman for the Bufalino crime family.",
    image: "/assets/images/the-ice-man.png",
    year: 2019,
    duration: "3h 29m",
    rating: 7.8,
    genres: ["Biography", "Crime", "Drama"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "R",
  },
  {
    id: 11,
    title: "Life",
    slug: "life",
    description:
      "A team of scientists aboard the ISS discover a rapidly evolving life form from Mars.",
    image: "/assets/images/black-p.png",
    year: 2017,
    duration: "1h 44m",
    rating: 6.6,
    genres: ["Sci-Fi", "Horror"],
    languages: ["English"],
    quality: "HD",
    pgRating: "R",
  },
  {
    id: 12,
    title: "Echoes",
    slug: "echoes",
    description:
      "Identical twins Leni and Gina have secretly swapped lives since they were children.",
    image: "/assets/images/ecehos.png",
    year: 2022,
    duration: "7 Episodes",
    rating: 5.9,
    genres: ["Drama", "Mystery"],
    languages: ["English"],
    quality: "HD",
    pgRating: "TV-MA",
  },
  {
    id: 13,
    title: "Shadow and Bone",
    slug: "shadow-and-bone",
    description: "Dark forces conspire against orphan mapmaker Alina Starkov.",
    image: "/assets/images/shadow-and-bone.png",
    year: 2021,
    duration: "2 Seasons",
    rating: 7.5,
    genres: ["Fantasy", "Adventure"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "TV-14",
  },
  {
    id: 14,
    title: "Money Heist",
    slug: "money-heist",
    description:
      "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history.",
    image: "/assets/images/dcotor-multyverce.png",
    year: 2017,
    duration: "5 Parts",
    rating: 8.2,
    genres: ["Action", "Crime"],
    languages: ["Spanish", "English"],
    quality: "HD",
    pgRating: "TV-MA",
  },
  {
    id: 15,
    title: "Peaky Blinders",
    slug: "peaky-blinders",
    description:
      "A gangster family epic set in 1900s England, centering on a gang who sew razor blades into their caps.",
    image: "/assets/images/peaky-blinders.png",
    year: 2013,
    duration: "6 Seasons",
    rating: 8.8,
    genres: ["Crime", "Drama"],
    languages: ["English"],
    quality: "HD",
    pgRating: "TV-MA",
  },
  {
    id: 16,
    title: "The Batman",
    slug: "the-batman",
    description:
      "Batman ventures into Gotham City's underworld when a sadistic killer leaves behind a trail of cryptic clues.",
    image: "/assets/images/dcotor-multyverce.png",
    year: 2022,
    duration: "2h 56m",
    rating: 7.8,
    genres: ["Action", "Crime"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "PG-13",
  },
  {
    id: 17,
    title: "Top Gun: Maverick",
    slug: "top-gun-maverick",
    description:
      "After thirty years, Maverick is still pushing the envelope as a top naval aviator.",
    image: "/assets/images/dcotor-multyverce.png",
    year: 2022,
    duration: "2h 10m",
    rating: 8.3,
    genres: ["Action", "Drama"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "PG-13",
  },
  {
    id: 18,
    title: "Everything Everywhere All at Once",
    slug: "everything-everywhere-all-at-once",
    description:
      "A Chinese-American immigrant is swept up in an insane adventure across the multiverse.",
    image: "/assets/images/shadow-and-bone.png",
    year: 2022,
    duration: "2h 19m",
    rating: 7.8,
    genres: ["Sci-Fi", "Comedy", "Action"],
    languages: ["English", "Mandarin"],
    quality: "HD",
    pgRating: "R",
  },
];
